# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-14 17:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('book_image', models.FileField(blank=True, upload_to=b'')),
                ('pdf', models.FileField(blank=True, upload_to='book/pdf')),
                ('book_branch', models.CharField(choices=[('CS', 'CS'), ('Mech', 'Mech'), ('ENTC', 'ENTC'), ('IT', 'IT'), ('CHEM', 'CHEM'), ('ETX', 'ETX'), ('Civil', 'Civil'), ('FY', 'FY')], default='CS', max_length=100)),
                ('book_sub', models.CharField(choices=[('DS', 'Data Structures'), ('DSGT', 'Data Structures and Graph Theory'), ('AM2', 'Applied Mathematcs'), ('AM1', 'Applied   \t\tMechanics'), ('EI', 'Engineering Informatics')], default='DS', max_length=100)),
                ('book_year', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], default='I', max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('edition', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2019, verbose_name='year')),
                ('sell_price', models.CharField(max_length=100)),
                ('rent_price_per_month', models.CharField(max_length=100, null=True)),
                ('rent_price_per_week', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ('sell_price',),
            },
        ),
        migrations.CreateModel(
            name='Ebook_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebook_name', models.CharField(blank=True, max_length=100)),
                ('ebook_image', models.FileField(blank=True, upload_to='ebook/img')),
                ('ebook_pdf', models.FileField(blank=True, upload_to='ebook/pdf')),
                ('ebook_author', models.CharField(max_length=100)),
                ('ebook_branch', models.CharField(choices=[('CS', 'CS'), ('Mech', 'Mech'), ('ENTC', 'ENTC'), ('IT', 'IT'), ('CHEM', 'CHEM'), ('ETX', 'ETX'), ('Civil', 'Civil'), ('FY', 'FY')], default='CS', max_length=100)),
                ('ebook_sub', models.CharField(choices=[('DS', 'Data Structures'), ('DSGT', 'Data Structures and Graph Theory'), ('AM2', 'Applied Mathematcs'), ('AM1', 'Applied Mechanics'), ('EI', 'Engineering Informatics')], default='DS', max_length=100)),
                ('ebook_year', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], default='I', max_length=100)),
                ('ebook_edition', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2019, null=True, verbose_name='year')),
                ('ebook_drive_url', models.URLField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enotes_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enotes_name', models.CharField(max_length=100)),
                ('enotes_image', models.FileField(blank=True, upload_to='enotes/img')),
                ('enotes_pdf', models.FileField(blank=True, upload_to='enotes/pdf')),
                ('enotes_branch', models.CharField(choices=[('CS', 'CS'), ('Mech', 'Mech'), ('ENTC', 'ENTC'), ('IT', 'IT'), ('CHEM', 'CHEM'), ('ETX', 'ETX'), ('Civil', 'Civil'), ('FY', 'FY')], default='CS', max_length=100)),
                ('enotes_sub', models.CharField(choices=[('DS', 'Data Structures'), ('DSGT', 'Data Structures and Graph Theory'), ('AM2', 'Applied Mathematcs'), ('AM1', 'Applied Mechanics'), ('EI', 'Engineering Informatics')], default='DS', max_length=100)),
                ('enotes_year', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], default='I', max_length=100)),
                ('enotes_author', models.CharField(choices=[('uploader', 'uploader'), ('teacher', 'teacher'), ('book', 'book'), ('google_internet', 'google/internet')], default='uploader', max_length=100)),
                ('enotes_author_name', models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Owner_model'), max_length=100)),
                ('enotes_drive_url', models.URLField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etx_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, null=True)),
                ('item_image', models.FileField(blank=True, upload_to=b'')),
                ('item_branch', models.CharField(choices=[('CS', 'CS'), ('Mech', 'Mech'), ('ENTC', 'ENTC'), ('IT', 'IT'), ('CHEM', 'CHEM'), ('ETX', 'ETX'), ('Civil', 'Civil'), ('FY', 'FY')], default='CS', max_length=100, null=True)),
                ('item_sub', models.CharField(choices=[('DS', 'Data Structures'), ('DSGT', 'Data Structures and Graph Theory'), ('AM2', 'Applied Mathematcs'), ('AM1', 'Applied   \t\tMechanics'), ('EI', 'Engineering Informatics'), ('None', 'none')], default='DS', max_length=100, null=True)),
                ('item_year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2019, null=True, verbose_name='year')),
                ('manufacturer', models.CharField(default='optional', max_length=100, null=True)),
                ('version', models.CharField(default='optional', max_length=100, null=True)),
                ('sell_price', models.CharField(max_length=100, null=True)),
                ('rent_price_per_month', models.CharField(default='60', max_length=100, null=True)),
                ('rent_price_per_week', models.CharField(default='20', max_length=100, null=True)),
            ],
            options={
                'ordering': ('sell_price',),
            },
        ),
        migrations.CreateModel(
            name='Novel_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel_name', models.CharField(max_length=100)),
                ('novel_image', models.FileField(blank=True, upload_to='novel/img')),
                ('novel_pdf', models.FileField(blank=True, upload_to='novel/pdf')),
                ('genre', models.CharField(choices=[('action', 'action'), ('fiction', 'fiction'), ('romance', 'romance'), ('comedy', 'comedy'), ('biography', 'biography'), ('tragedy', 'tragedy'), ('thriller', 'thriller'), ('classic', 'classic'), ('mystery', 'mystery'), ('children', 'children'), ('None', 'None')], default='classic', max_length=100, null=True)),
                ('author', models.CharField(default='optional', max_length=100, null=True)),
                ('edition', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2019, null=True, verbose_name='year')),
                ('pages', models.CharField(default='250', max_length=100, null=True)),
                ('sell_price', models.CharField(default='300', max_length=100, null=True)),
                ('rent_price_per_month', models.CharField(default='150', max_length=100, null=True)),
                ('rent_price_per_week', models.CharField(default='25', max_length=100, null=True)),
            ],
            options={
                'ordering': ('sell_price',),
            },
        ),
        migrations.CreateModel(
            name='Owner_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_num', models.CharField(max_length=100, null=True, verbose_name='phone number')),
                ('ac_year', models.CharField(max_length=100, null=True, verbose_name='academic year')),
                ('branch', models.CharField(max_length=100, null=True, verbose_name='branch')),
                ('email_id', models.EmailField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('dp', models.FileField(blank=True, upload_to='owner/pdf')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='novel_model',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Owner_model'),
        ),
        migrations.AddField(
            model_name='etx_model',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Owner_model'),
        ),
        migrations.AddField(
            model_name='enotes_model',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Owner_model'),
        ),
        migrations.AddField(
            model_name='ebook_model',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Owner_model'),
        ),
        migrations.AddField(
            model_name='book_model',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Owner_model'),
        ),
    ]
