# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-14 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_owner_model_email_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_model',
            name='material_name',
        ),
    ]
