# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-15 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190415_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_model',
            name='book_sub',
            field=models.CharField(choices=[('NO SUBJECT', 'NO SUBJECT'), ('DSF', 'Data Structures And Files'), ('DSGT', 'Data Structures and Graph Theory'), ('AM2', 'Applied Mathematcs'), ('AM1', 'Applied Mechanics'), ('EI', 'Engineering Informatics'), ('DBMS', 'DBMS'), ('SYSTEM ENGG', 'SYSTEM ENGG'), ('MATHS', 'MATHS'), ('PSYCHO', 'PSYCHO'), ('MATERIAL ENGG', 'MATERIAL ENGG'), ('PYTHON', 'PYTHON'), ('CPP', 'CPP'), ('EEE', 'EEE'), ('None', 'none')], default='NO SUBJECT', max_length=100),
        ),
        migrations.AlterField(
            model_name='enotes_model',
            name='enotes_sub',
            field=models.CharField(choices=[('NO SUBJECT', 'NO SUBJECT'), ('DSF', 'Data Structures And Files'), ('DSGT', 'Data Structures and Graph Theory'), ('AM2', 'Applied Mathematcs'), ('AM1', 'Applied Mechanics'), ('EI', 'Engineering Informatics'), ('DBMS', 'DBMS'), ('SYSTEM ENGG', 'SYSTEM ENGG'), ('MATHS', 'MATHS'), ('PSYCHO', 'PSYCHO'), ('MATERIAL ENGG', 'MATERIAL ENGG'), ('PYTHON', 'PYTHON'), ('CPP', 'CPP'), ('EEE', 'EEE'), ('None', 'none')], default='NO SUBJECT', max_length=100),
        ),
        migrations.AlterField(
            model_name='etx_model',
            name='item_sub',
            field=models.CharField(choices=[('NO SUBJECT', 'NO SUBJECT'), ('DSF', 'Data Structures And Files'), ('DSGT', 'Data Structures and Graph Theory'), ('AM2', 'Applied Mathematcs'), ('AM1', 'Applied Mechanics'), ('EI', 'Engineering Informatics'), ('DBMS', 'DBMS'), ('SYSTEM ENGG', 'SYSTEM ENGG'), ('MATHS', 'MATHS'), ('PSYCHO', 'PSYCHO'), ('MATERIAL ENGG', 'MATERIAL ENGG'), ('PYTHON', 'PYTHON'), ('CPP', 'CPP'), ('EEE', 'EEE'), ('None', 'none')], default='NO SUBJECT', max_length=100, null=True),
        ),
    ]
