# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-25 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190415_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_model',
            name='book_image',
            field=models.FileField(blank=True, default='book/pdf/no_image.jpg', upload_to=b''),
        ),
    ]
