# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-28 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190709_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etx_model',
            old_name='item_name',
            new_name='item_keyword1',
        ),
        migrations.RemoveField(
            model_name='etx_model',
            name='item_branch',
        ),
        migrations.RemoveField(
            model_name='etx_model',
            name='item_sub',
        ),
        migrations.RemoveField(
            model_name='etx_model',
            name='item_year',
        ),
        migrations.AddField(
            model_name='etx_model',
            name='item_keyword2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etx_model',
            name='item_keyword3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etx_model',
            name='item_keyword4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etx_model',
            name='rent_price_per_day',
            field=models.CharField(default='15', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='etx_model',
            name='rent_price_per_month',
            field=models.CharField(default='250', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='etx_model',
            name='rent_price_per_week',
            field=models.CharField(default='100', max_length=100, null=True),
        ),
    ]
