# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-28 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190728_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etx_model',
            name='item_keyword2',
            field=models.CharField(default='optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='etx_model',
            name='item_keyword3',
            field=models.CharField(default='optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='etx_model',
            name='item_keyword4',
            field=models.CharField(default='optional', max_length=100, null=True),
        ),
    ]
