# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-28 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20190728_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etx_model',
            name='item_image',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
