# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-29 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20190728_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arduino_model',
            fields=[
                ('etx_model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.Etx_model')),
                ('type', models.CharField(choices=[('mega', 'mega'), ('uno', 'uno'), ('nano', 'nano'), ('mini', 'mini')], default='uno', max_length=100)),
                ('cable', models.BooleanField(default=True)),
                ('jumper_wires', models.CharField(choices=[('m2m', 'm2m'), ('m2f', 'm2f'), ('f2f', 'f2f'), ('none', 'none')], default='none', max_length=100)),
                ('jumper_qty', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('sell_price',),
            },
            bases=('polls.etx_model',),
        ),
        migrations.RemoveField(
            model_name='etx_model',
            name='item_keyword1',
        ),
        migrations.RemoveField(
            model_name='etx_model',
            name='item_keyword2',
        ),
        migrations.RemoveField(
            model_name='etx_model',
            name='item_keyword3',
        ),
        migrations.RemoveField(
            model_name='etx_model',
            name='item_keyword4',
        ),
        migrations.RemoveField(
            model_name='etx_model',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='etx_model',
            name='version',
        ),
        migrations.AddField(
            model_name='etx_model',
            name='item_image2',
            field=models.FileField(blank=True, default='book/pdf/no_image.jpg', upload_to=b''),
        ),
        migrations.AddField(
            model_name='etx_model',
            name='item_image3',
            field=models.FileField(blank=True, default='book/pdf/no_image.jpg', upload_to=b''),
        ),
    ]
