# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-29 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20190729_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arduino_model',
            old_name='type',
            new_name='type_A',
        ),
    ]
