# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-29 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20190729_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calc_model',
            fields=[
                ('etx_model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.Etx_model')),
                ('type_A', models.CharField(choices=[('Casio FX-991MS', 'Casio FX-991MS'), ('Casio FX-991ES', 'Casio FX-991ES'), ('other', 'other')], default='Casio FX-991MS', max_length=100)),
                ('desc', models.CharField(default='anything else you wanna tell about calc', max_length=100)),
            ],
            options={
                'ordering': ('sell_price',),
            },
            bases=('polls.etx_model',),
        ),
    ]
