# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-31 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20190729_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel_model',
            name='novel_pdf',
        ),
        migrations.AddField(
            model_name='novel_model',
            name='novel_desc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='novel_model',
            name='rent_price_per_day',
            field=models.CharField(default='25', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ebook_model',
            name='ebook_drive_url',
            field=models.URLField(default='http://localhost:8000/polls/', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ebook_model',
            name='ebook_image',
            field=models.FileField(blank=True, default='book/pdf/no_image.jpg', upload_to='ebook/img'),
        ),
        migrations.AlterField(
            model_name='enotes_model',
            name='enotes_image',
            field=models.FileField(blank=True, default='book/pdf/no_image.jpg', upload_to='enotes/img'),
        ),
        migrations.AlterField(
            model_name='novel_model',
            name='novel_image',
            field=models.FileField(blank=True, default='book/pdf/no_image.jpg', upload_to='novel/img'),
        ),
        migrations.AlterField(
            model_name='novel_model',
            name='rent_price_per_week',
            field=models.CharField(default='50', max_length=100, null=True),
        ),
    ]
