# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-01 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20190801_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enotes_model',
            name='enotes_name',
        ),
    ]
