# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-01 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20190801_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enotes_model',
            name='enotes_date',
            field=models.DateField(),
        ),
    ]
