# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-05 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20190801_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enotes_model',
            name='enotes_author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enotes_model',
            name='enotes_unit',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
