# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-05 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20190805_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_model',
            name='rent_price_per_day',
            field=models.CharField(default=20, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book_model',
            name='rent_price_per_month',
            field=models.CharField(default=100, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book_model',
            name='rent_price_per_week',
            field=models.CharField(default=50, max_length=100, null=True),
        ),
    ]
